name: Sync to GitLab
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
    paths:
      - "**"

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "mirror@github.actions"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/devanonitos/docustarter.git
          git push gitlab main --force || echo "⚠️ Mirror to GitLab failed, please check token or network."
